# training datasets
ADE20K: /workspace/stereo-from-mono/workdata/ADE20K
diode: /workspace/stereo-from-mono/workdata/diode
diw: /workspace/stereo-from-mono/workdata/diw/
mapillary: /workspace/stereo-from-mono/workdata/mapillary/
mscoco: /workspace/stereo-from-mono/workdata/mscoco/
sceneflow: /workspace/stereo-from-mono/workdata/sceneflow/ # not yet

# testing datasets
eth3d: /workspace/stereo-from-mono/workdata/ETH3D/
flicker: /workspace/stereo-from-mono/workdata/flicker1024
kitti2015: /workspace/stereo-from-mono/workdata/kitti/stereo/ # not yet
kitti2012: /workspace/stereo-from-mono/workdata/kitti/stereo2012/ # not yet
middlebury: /workspace/stereo-from-mono/workdata/middlebury/ # not yet
dexter: /workspace/stereo-from-mono/workdata/dexter